# Generated by Django 4.2.19 on 2025-02-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados',
            options={'permissions': [('view_arquivos_enviados', 'Can view Arquivos Enviados'), ('import_csv', 'Can import CSV'), ('train_knn', 'Can train KNN')]},
        ),
    ]
