# Generated by Django 4.2.19 on 2025-02-24 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_alter_dados_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados',
            options={},
        ),
    ]
