# Generated by Django 4.2.19 on 2025-02-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_pessoa_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='user',
        ),
    ]
